### ISSUE TITLE
Search functionality

### ISSUE THREAD

**Issue by jcalcaben** [magento-research/pwa-devdocs#19]
## This issue is a:
[ ] Bug
[ ] New Topic Request
[ ] Topic Clarification Request
[X] New Feature Request
[ ] Other
 

## Description:

There is currently no way to search the docs.
 

## Expected Result:

A search bar appears on the top right and on the front page.
Entering a search term returns relevant page results.
 

## Possible Solutions:

~~Integrate [Lunr] search into the site.~~

Implement Algolia search.
 
[Lunr]: https://lunrjs.com/

**Comment by belbiy** [comment]
James, i'll make Algolia search work with the site. We might even add the multi-index search so results from this site will appear in devdocs (and vice versa).

**Comment by jcalcaben** [comment]
Completed as part of #27 thanks @belbiy !
