### ISSUE TITLE
[SPIKE] Getting Started: Basic Concepts (Documentation) 

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-devdocs#2]
As a developer I want to understand the basic concepts of Magento PWA so that I can contribute or create a PWA storefront with it.

- Binding Components to Data
- Root Components and Routing (edited)
- Loading and Offline States
- Client State, Reducers, and Actions (edited)
- CSS Modules
- Critical Path
- Performance Patterns
- Extensibility with Containers (and other concepts TBD)

AC
- Review of current lower-level concepts from Zetlen and team
- Creation of a plan and sample fontent for Magento PWA Documentation and related documentation

**Comment by jcalcaben** [comment]
Issues created as a result of this Spike:

- #8 
- #9 
- #10 
- #11 
- #12 
- #13 
- #14 
- #15 
- #16 
- #17 
- #18
