### ISSUE TITLE
Additions to Peregrine reference documentation

### ISSUE THREAD

**Issue by ericerway** [magento-research/pwa-devdocs#32]
As a developer I want to learn about the Peregrine components for PWA Studio so that I can use them in a reference store.

AC
- Documentation for simulators and lists
- Review (as needed)

**Comment by zetlen** [comment]
@jcalcaben Had a quick chat about definition of done and we agreed that you can call this done when it's merged, not only when it's released. Would you like to merge it?

**Comment by jcalcaben** [comment]
@zetlen Merged (but not published).
